### ISSUE TITLE
Attaching a specific PDF file results in an error and crash. The file draft then cannot be dismissed.

### ISSUE THREAD

**Issue by nehemiagurl** [signalflatpak/signal#15]
Attaching a specific PDF file results in the following error, then a crash:

> Render process is gone
> 
> Error: Reason: killed, Exit Code: 3
>     at App.<anonymous> ([REDACTED]/app/global_errors.js:94:7)
>     at App.emit (node:events:519:28)
>     at WebContents.<anonymous> (node:electron/js2c/browser_init:2:87106)
>     at WebContents.emit (node:events:519:28)
> 
> App Version: 7.28.0
> OS: linux

The file isn't corrupted and can be opened normally in Okular. No other PDF file seems to cause this error.
Once attaching this file to a chat, a draft with the broken attachment be created. The file can't be removed from the message, nor can the message be sent empty like with usual attachments.
[Screencast_20241014_180151.webm](https://github.com/user-attachments/assets/d2f044ca-eb85-4c86-b90b-53f5349ec4a1)
However, when typing text into the message box and sending, a regular, attachment-less message is sent.

Is this something to send to upstream? Is this an issue with this specific version?

**Comment by adamthiede** [comment]
Thanks for the report. A few questions:

- which architecture and package format? This repo provides flatpaks and .debs for arm64 and amd64.
- Would you be comfortable sharing the pdf?
- Does this happen also with the flathub flatpak or signal's official .deb?

**Comment by nehemiagurl** [comment]
I am using the arm64 flatpak.
As the PDF contains far too much personal information I will not be sharing it. Sorry. I understand this may prove challenging to debug for that reason.
Just had someone test the same file on the Flathub Flatpak on x86_64 and the issue is not reproducible on their end. I'll try and see if I can also get an ubuntu machine and test with the official .deb.

**Comment by adamthiede** [comment]
Thanks - and no worries on not sharing the PDF. It's just that attachment though, and other things work fine? Is it really big?

Currently the portal stuff is broken on this flatpak due to upstream electron issues, and we've not changed the flatpak to request full disk access, since that's not a great idea I think. Have you used flatseal or something else to give the flatpak permissions to attach files, or did you move the pdf to the .var/app/org.signal.Signal directory?

**Comment by nehemiagurl** [comment]
it's just this attachment. nothing else seems to trigger it. the file is simply in the Downloads folder - all other downloads folder files work just fine. the file isn't particularly big, it's actually quite small - only 73KB.
I didn't use flatseal, at least not directly - I've used KDE's built in "Flatpak permission" to grand access to grant filesystem access to specific paths (Downloads among them) so I can select files from there. Nothing beyond that.

**Comment by adamthiede** [comment]
If you run signal from the command line (`flatpak run org.signal.Signal`) what is the output it gives when adding the attachment?
If you have a way to modify the pdf (maybe add a comment or annotate it somehow?) does the modified version trigger it?

**Comment by nehemiagurl** [comment]
I figured out what differentiates this file from other files! It contains Hebrew characters in the file name. I tried changing other files to have even a single Hebrew character in their name, and they also resulted in a crash.
using a random pic from Wikimedia to test, this file titled `test file 1.jpg` loads normally:
![test file 1](https://github.com/user-attachments/assets/302d5d95-9d7e-4151-9b4d-1241f1990b41)
but take the same file, don't even duplicate it just rename it to `test file 1א.jpg`, and it crashes:
![test file 1א](https://github.com/user-attachments/assets/be9b1fea-fc5a-402a-8319-1874a0717b32)

very weirdly though, when starting Signal from the command line, the file uploads normally. when starting from the GUI (be it KDE's Task Manager or Application Launcher or even from Discover) it still crashes. this is true for all files tested containing Hebrew characters.
this doesn't resolved previously failed uploads though, the issue documented in [this video I've uploaded earlier](https://github.com/user-attachments/assets/d2f044ca-eb85-4c86-b90b-53f5349ec4a1) still holds and the way to dismiss is still the same (add text and send the message which will be sent without the attachment). only new uploads when starting from the command line aren't affected.

**Comment by adamthiede** [comment]
Well that's not ideal; I assume if you've got one file with Hebrew characters you've probably got more.

What OS are you using? I don't use KDE but I assume there's a way to tell it which locale(s) to use. Something tells me that it's probably a configuration issue given that it works correctly from the command line.

If you modify the .desktop file or create a custom one and use something like `flatpak run org.signal.Signal` for the `Exec` line, I wonder if that may help.

**Comment by nehemiagurl** [comment]
I'm running Fedora Asahi Remix on a Mac (hence ARM64 and using this instead of the flathub flatpak) with KDE Plasma 6.2.0.
The application launcher .desktop file is as follows:
`Exec=/usr/bin/flatpak run --branch=master --arch=aarch64 --command=signal-desktop --file-forwarding org.signal.Signal @@u %U @@`
so it doesn't look like this is the source of the problem? I mean running that exec line in the terminal results in a non-crashing version.
I must admit I'm not that versed in flatpak .desktop files. there are ultimately two .desktop files nested somewhere within `~/.local/share/flatpak/app/org.signal.Signal`, one has the same exec line as the application launcher's, the second has:
`Exec=signal-desktop %U`

**Comment by adamthiede** [comment]
I just installed a Fedora 40 KDE spin VM and was not able to reproduce the issue. Granted the difference is x86 vs arm64, and I'm not sure how closely Asahi tracks "real" Fedora, but I'd expect they are similar. I've run `dnf list --installed` and put the list here: https://termbin.com/x8mq
Maybe compare your installed packages to this one? See if this list has any you don't have.

**Comment by adamthiede** [comment]
Oh, and another question - is this using a "user" or "system" remote? If one, maybe try the other?

**Comment by nehemiagurl** [comment]
just reproduced this bug again, this time not with hebrew characters but with §.
i think i missed your previous comments and the termbin file has been deleted, can you reupload?
switching to a system remote resulted in the same error. and as always running from the command line the bug is not reproducible, only when using one of the desktop file shortcuts.

**Comment by adamthiede** [comment]
I've installed Fedora 41 (since that's the current version now) KDE in a vm and this is the `dnf list --installed` output: https://termbin.com/qup3

**Comment by nehemiagurl** [comment]
there seem to be quite a few, i spotted at least a few dozen. though since asahi is still on 40, maybe that was the more appropirate comparison.
here's some just from the very top of the list
```
SDL2_ttf.x86_64
aardvark-dns.x86_64
akregator.x86_64
akregator-libs.x86_64
anaconda.x86_64
anaconda-install-env-deps.x86_64
anaconda-live.noarch
aribb24.x86_6
calendarsupport.x86_64
catatonit.x86_64
conmon.x86_64
container-selinux.noarch
containers-common.noarch
containers-common-extra.noarch
```
(strictly missing packages, not different versions)
so it's a bit hard to tell what's relevant and what's not.

**Comment by adamthiede** [comment]
See if there's anything regarding locales or languages?

Check if there are any locale or language settings in KDE that you can change. What does `locale -a` and `locale` print on the command line? Do you have fonts installed for these languages, like the noto cjk set? (try installing [google-noto-cjk-fonts](https://src.fedoraproject.org/rpms/google-noto-cjk-fonts) )

**Comment by nehemiagurl** [comment]
local:
```
LANG=en_DK.UTF-8
LC_CTYPE="en_DK.UTF-8"
LC_NUMERIC=he_IL.utf8
LC_TIME=he_IL.utf8
LC_COLLATE="en_DK.UTF-8"
LC_MONETARY=he_IL.utf8
LC_MESSAGES="en_DK.UTF-8"
LC_PAPER=he_IL.utf8
LC_NAME=he_IL.utf8
LC_ADDRESS=he_IL.utf8
LC_TELEPHONE=he_IL.utf8
LC_MEASUREMENT=he_IL.utf8
LC_IDENTIFICATION=he_IL.utf8
LC_ALL=
```
locale -a 
https://pb.envs.net/?ab39411782aa85b7#6cQ8g2zzaFv9BFUvRREWWATWSkHUna8DE8Y7zu2aAX3E
(i'm pretty sure this is just the default list?)

as for fonts, i have all the noto families installed by default including the cjk family, and the following configured as the system fonts:
![Screenshot_20241120_212900](https://github.com/user-attachments/assets/72db7c7c-1926-479a-b85b-61a5c4ae7122)
changing those to be "noto sans hebrew" did not help.
the only font family i've installed on my own is Alef.

**Comment by nehemiagurl** [comment]
happened again with a file whose name contains Hebrew characters:
```
Render process is gone

Error: Reason: killed, Exit Code: 3
    at EventEmitter.<anonymous> (bundles:///main.js:12:2281)
    at EventEmitter.emit (node:events:509:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:103007)
    at WebContents.emit (node:events:509:28)

App Version: 8.24.1
OS: linux
```
no crash on the new beta aarch64 AppImage.

**Comment by adamthiede** [comment]
https://github.com/flathub/org.signal.Signal/issues/137#issuecomment-5263643651

Does this happen with the new deb-as-flatpak? Would help figure out if it's an issue with this package, your locale config, flatpak packaging in general, etc.
